export const HEALTHWELLNESS = [
  {
    id: 0,
    header: "Make Time for Yourself and exercise regularly",
    image1: "",
    alt: "",
    image2: "",
    alt: "",
    description:
      'There are alot of inexpensive ways to get active, without having to buy a gym membership. In fact, the COVID-19 pandemic drove alot of people to become creative, with the closure of gyms, and homes and bedrooms have been turned into mini gyms. Additionally, alot of apps which required subscriptions are no longer charging and promise not to charge throughout the pandemic. There are tons of resources online, such as <a href="Youtube.com">Youtube.com</a>, Nike has an awesome app called <a href="https://apps.apple.com/us/app/nike-training-club/id301521403">NTC</a>, and most gyms have reverted to offering live and pre-recorded programs through apps. Now a word on committing, if you pre-register for fitness classes at the beginning of the week, you’ll be more committed to attending. And even still, give yourself time to decompress and relax, whether it’s a night at home, laughing with your friends, or being around family.',
    sub_description: "",
    sub_header: "",
    link: "",
  },
  {
    id: 1,
    header: "Take very good care of yourself during this Covid-19 pandemic",
    image1: "",
    alt: "",
    image2: "",
    alt: "",
    description: "",
    sub_description:
      "It is important to stay in touch with your body temperature. Sometimes our body gives us hunger signs when really we are just too cold! Studies show that we do tend to gain a few pounds in winter since food, of course, can give us a very comforting feeling. So just do a body check. And when in doubt, warm up to some raw chocolate and tea by a fire.",
    sub_header: "Check Your Body Temp",
    link: "https://www.cdc.gov/coronavirus/2019-ncov/index.html",
  },
  {
    id: 2,
    header: "Do yoga and meditate",
    image1: "/assets/img/Yogahead.jpg.png",
    alt: "Yoga",
    image2: "/assets/img/black_yoga.jpg",
    alt: "Yoga",
    description:
      "Yoga and meditation are good for centering yourself and clearing your mind. Meditation deals with mental relaxtion and concentration and is a part of yoga.",
    sub_description: "",
    sub_header: "",
    link: "https://www.yogajournal.com/meditation/benefits-of-meditation",
  },
  {
    id: 3,
    header: "Maintain mental wellness",
    image1: "/assets/img/mental-health.jpg",
    alt: "",
    image2: "",
    alt: "",
    description:
      "Most of us only focus on maintaining good physical health, without addressing our mental health to create that balance. The stigma this once was is being alleviated slowly, because more people are addressing it. The pandemic and police brutality towards people of color, are having an effect on people's mental health. Mental health includes our emotional, psychological, and social well-being. It affects how we think, feel, and act. It also helps determine how we handle stress, relate to others, and make choices. Mental health is important at every stage of life, from childhood and adolescence through adulthood.",
    sub_description: "",
    sub_header: "",
    link: "",
  },

  {
    id: 4,
    header: "Drink Golden Milk",
    image1: "/assets/img/Winter-Wellness-Tips-Body5.jpg",
    alt: "Golden milk",
    image2: "/assets/img/Winter-Wellness-Tips-Body6.jpg",
    alt: "Golden milk",
    description:
      "I actually discovered this drink on a flight, while purusing one of those magazines they provide in the seat in front of you. The main ingredient of Golden milk is turmeric. (Turmeric is a potent anti-inflammatory that exhibits over 150 potentially therapeutic activities, including antimicrobial activity as well as boosts for the immune system.) It's a great recipe for Health and Wellness. Make it today; you won’t regret it!",
    sub_description: "",
    sub_header: "",
    link: "https://simpleveganblog.com/golden-milk/",
  },
  {
    id: 5,
    header: "Get Creative With Your Crockpot",
    image1: "/assets/img/Winter-Wellness-Tips-Body5.jpg",
    alt: "Golden milk",
    image2: "/assets/img/Winter-Wellness-Tips-Body6.jpg",
    alt: "Golden milk",
    description:
      "My crockpot gets an intense workout week after week during the winter. I tend to crave, like a lot of people, more hearty foods when the temperatures drop. But try to stick to ingredients that are seasonal to keep meals nutrient-dense and full of flavor. Some staples in my recipes this winter have been green beans, sweet potatoes, citrus, pomegranates and brussels sprouts to name a few.",
    sub_description: "",
    sub_header: "",
    link: "https://simpleveganblog.com/golden-milk/",
  },
  {
    id: 6,
    header: "Eat Local When Eating Out",
    image1: "/assets/img/Chloe.jpg",
    alt: "Burger",
    image2: "/assets/img/Burger_Kombucha.jpg",
    alt: "Burger",
    description:
      "We all love to eat out every once in a while. It is a great way to spend precious time with friends and enjoy some relaxation away from the kitchen. It's good to look at ingredients being locally grown, organic, and fresh. If you happen to be in New York City, or other cities like, London, Toronto, check out By Chloe – a vegan burger, air baked sweet potato fries with beet ketchup and Kombucha to sip on.",
    sub_description: "",
    sub_header: "",
    link: "",
  },
];
