export const HOMEIMAGES = [
  {
    id: 0,
    name: "Yellow squash",
    image: "/assets/img/cooked_squash.jpg",
    alt: "Yellow squash",
    param: "Vegetables&Fruits",
    title: "Vegetables & Fruits",
    li1: "VEGAN",
    li2: "FOOD",
    navlinkpath: "food",
    component: "",
    section: "Squash",
    title: "Healthy Eats",
    colsize: "col-4",
    width: "10%",
  },
  {
    id: 1,
    name: "Squash soup",
    image: "/assets/img/squash_soup.jpg",
    alt: "Cooked squash",
    param: "Vegetables&Fruits",
    title: "Vegetables & Fruits",
    li1: "VEGAN",
    li2: "FOOD",
    navlinkpath: "food",
    component: "Food",
    section: "Squash",
    title: "Soups",
    colsize: "col-3",
    width: "10%",
  },

  {
    id: 2,
    name: "Sundried tomatoes",
    image: "/assets/img/sundried_tomatoes.jpg",
    alt: "Cooked squash",
    param: "Vegetables&Fruits",
    title: "Vegetables & Fruits",
    li1: "VEGAN",
    li2: "FOOD",
    navlinkpath: "food",
    component: "Food",
    section: "Tomatoes",
    title: "Condiments",
    colsize: "col-4",
    width: "20%",
  },

  {
    id: 3,
    name: "Dairy Alternatives",
    image: "/assets/img/Non-dairy_milk.jpg",
    alt: "Cooked squash",
    param: "Vegetables&Fruits",
    title: "Vegetables & Fruits",
    li1: "VEGAN",
    li2: "DAIRY FREE",
    navlinkpath: "food",
    component: "Food",
    section: "DairyFreeMilk",
    title: "Dairy Alternatives",
    colsize: "col-4",
    width: "38%",
  },
  {
    id: 4,
    name: "Green juice",
    image: "/assets/img/green_juice.jpg",
    alt: "Green juice",
    param: "Vegetables&Fruits",
    title: "Vegetables & Fruits",
    li1: "HEALTHY",
    li2: "JUICING",
    navlinkpath: "food",
    component: "Food",
    section: "Juicing",
    title: "Juicing",
    colsize: "col-3",
    width: "38%",
  },
  {
    id: 5,
    name: "Fruit salad",
    image: "/assets/img/fruit_salad.jpg",
    alt: "Fruit salad",
    param: "Vegetables&Fruits",
    title: "Vegetables & Fruits",
    li1: "HEALTHY",
    li2: "FRUITS",
    navlinkpath: "food",
    component: "Food",
    section: "Fruits",
    title: "Fruit salad",
    colsize: "col-4",
    width: "24%",
  },
  {
    id: 6,
    name: "Mushroom burger",
    image: "/assets/img/Mushroom_burger.jpg",
    alt: "Mushroom burger",
    param: "Meatless&Options",
    title: "Meatless Options",
    li1: "VEGAN",
    li2: "FOOD",
    navlinkpath: "vegan",
    component: "",
    section: "Grains",
    title: "Meatless burger",
    colsize: "col-3",
    width: "40%",
  },
  {
    id: 7,
    name: "Quinoa",
    image: "/assets/img/quinoa-grains.jpg",
    alt: "Quinoa",
    param: "Meatless&Options",
    title: "Meatless Options",
    li1: "VEGAN",
    li2: "FOOD",
    navlinkpath: "vegan",
    component: "",
    section: "Grains",
    title: "Quinoa",
    colsize: "col-4",
    width: "30%",
  },
  {
    id: 8,
    name: "Meatless",
    image: "/assets/img/meatless.jpg",
    alt: "Meatless",
    param: "Meatless&Options",
    title: "Meatless Options",
    li1: "VEGAN",
    li2: "FOOD",
    navlinkpath: "vegan",
    component: "",
    section: "Meat substitutes",
    title: "Other Meatless Options",
    colsize: "col-3",
    width: "30%",
  },
  {
    id: 9,
    name: "Keeping fit",
    image: "/assets/img/girl-mode-tapis.jpg",
    alt: "Fitness",
    param: "Health&and&Wellness",
    title: "Health and Wellness",
    li1: "WELLNESS",
    li2: "EXERCISING",
    navlinkpath: "healthwellness",
    component: "",
    section: "IN WELLNESS",
    title: "Keeping fit",
    colsize: "col-3",
    width: "30%",
  },
  {
    id: 10,
    name: "Yoga",
    image: "/assets/img/black_yoga.jpg",
    alt: "Yoga",
    param: "Health&and&Wellness",
    title: "Health and Wellness",
    li1: "WELLNESS",
    li2: "YOGA",
    navlinkpath: "healthwellness",
    component: "",
    section: "",
    title: "Yoga",
    colsize: "col-3",
    width: "30%",
  },
  {
    id: 11,
    name: "Mental Wellness",
    image: "/assets/img/mental-health.jpg",
    alt: "Mental Health",
    param: "Health&and&Wellness",
    title: "Health and Wellness",
    li1: "Vegan",
    li2: "Food",
    navlinkpath: "healthwellness",
    component: "",
    section: "",
    title: "Mental Wellness",
    colsize: "col-4",
    width: "40%",
  },
  {
    id: 12,
    name: "Travelling",
    image: "/assets/img/wellness.jpg",
    alt: "Wellness",
    param: "Travel&for&wellness",
    title: "Travel and Wellness",
    li1: "Vegan",
    li2: "Food",
    navlinkpath: "travel",
    component: "",
    section: "",
    title: "Travelling",
    colsize: "col-4",
    width: "40%",
  },
  {
    id: 13,
    name: "Staycation",
    image: "/assets/img/books_reading.jpg",
    alt: "Staycation",
    param: "Travel&for&wellness",
    title: "Travel and Wellness",
    li1: "Vegan",
    li2: "Food",
    navlinkpath: "travel",
    component: "",
    section: "",
    title: "Staycation",
    colsize: "col-3",
    width: "24%",
  },
  {
    id: 14,
    name: "Mental Wellness",
    image: "/assets/img/meditate.jpg",
    alt: "Meditate",
    param: "Travel&for&wellness",
    title: "Travel and Wellness",
    li1: "Vegan",
    li2: "Food",
    navlinkpath: "travel",
    component: "",
    section: "",
    title: "Mental Wellness",
    colsize: "col-4",
    width: "36%",
  },
  {
    id: 15,
    name: "Fashion",
    image: "/assets/img/Ethical_fashion.png",
    alt: "Ethical Fashion",
    param: "Fashion",
    title: "Fashion",
    li1: "Vegan",
    li2: "Food",
    navlinkpath: "fashion",
    component: "",
    section: "",
    title: "Ethical Fashion",
    colsize: "col-4",
    width: "35%",
  },
  {
    id: 16,
    name: "Fashion",
    image: "/assets/img/Fashion_men.jpg",
    alt: "Fashion",
    param: "Fashion",
    title: "Fashion",
    li1: "Vegan",
    li2: "Food",
    navlinkpath: "fashion",
    component: "",
    section: "",
    title: "Sustainable Fashion",
    colsize: "col-3",
    width: "35%",
  },
  {
    id: 17,
    name: "Fashion",
    image: "/assets/img/styles.jpg",
    alt: "Fashion",
    param: "Fashion",
    title: "Fashion",
    li1: "Vegan",
    li2: "Food",
    navlinkpath: "fashion",
    component: "",
    section: "",
    title: "Fashion",
    colsize: "col-3",
    width: "30%",
  },
];
